/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/ElementsFieldPlayersLeader': RouteRecordInfo<'/ElementsFieldPlayersLeader', '/ElementsFieldPlayersLeader', Record<never, never>, Record<never, never>>,
    '/ElementsFieldPlayersPenalties': RouteRecordInfo<'/ElementsFieldPlayersPenalties', '/ElementsFieldPlayersPenalties', Record<never, never>, Record<never, never>>,
    '/ElementsGoaliesLeader': RouteRecordInfo<'/ElementsGoaliesLeader', '/ElementsGoaliesLeader', Record<never, never>, Record<never, never>>,
    '/ElementsSchedule': RouteRecordInfo<'/ElementsSchedule', '/ElementsSchedule', Record<never, never>, Record<never, never>>,
    '/ElementsStandings': RouteRecordInfo<'/ElementsStandings', '/ElementsStandings', Record<never, never>, Record<never, never>>,
    '/ElementsTeamAttendance': RouteRecordInfo<'/ElementsTeamAttendance', '/ElementsTeamAttendance', Record<never, never>, Record<never, never>>,
    '/ElementsTeamFairplay': RouteRecordInfo<'/ElementsTeamFairplay', '/ElementsTeamFairplay', Record<never, never>, Record<never, never>>,
    '/ElementsTeamPenaltyKilling': RouteRecordInfo<'/ElementsTeamPenaltyKilling', '/ElementsTeamPenaltyKilling', Record<never, never>, Record<never, never>>,
    '/ElementsTeamPowerplay': RouteRecordInfo<'/ElementsTeamPowerplay', '/ElementsTeamPowerplay', Record<never, never>, Record<never, never>>,
    '/ElementsTeamScoringEfficiency': RouteRecordInfo<'/ElementsTeamScoringEfficiency', '/ElementsTeamScoringEfficiency', Record<never, never>, Record<never, never>>,
    '/ExtendedChampionship': RouteRecordInfo<'/ExtendedChampionship', '/ExtendedChampionship', Record<never, never>, Record<never, never>>,
    '/ExtendedIvrIdentifiers': RouteRecordInfo<'/ExtendedIvrIdentifiers', '/ExtendedIvrIdentifiers', Record<never, never>, Record<never, never>>,
    '/ExtendedScheduleCup': RouteRecordInfo<'/ExtendedScheduleCup', '/ExtendedScheduleCup', Record<never, never>, Record<never, never>>,
    '/GameCenter': RouteRecordInfo<'/GameCenter', '/GameCenter', Record<never, never>, Record<never, never>>,
    '/LigaPlayer': RouteRecordInfo<'/LigaPlayer', '/LigaPlayer', Record<never, never>, Record<never, never>>,
    '/LigaPlayers': RouteRecordInfo<'/LigaPlayers', '/LigaPlayers', Record<never, never>, Record<never, never>>,
    '/LigaPlayoffs': RouteRecordInfo<'/LigaPlayoffs', '/LigaPlayoffs', Record<never, never>, Record<never, never>>,
    '/LigaSchedule': RouteRecordInfo<'/LigaSchedule', '/LigaSchedule', Record<never, never>, Record<never, never>>,
    '/LigaStandings': RouteRecordInfo<'/LigaStandings', '/LigaStandings', Record<never, never>, Record<never, never>>,
    '/LigaStatistics': RouteRecordInfo<'/LigaStatistics', '/LigaStatistics', Record<never, never>, Record<never, never>>,
    '/LigaTeam': RouteRecordInfo<'/LigaTeam', '/LigaTeam', Record<never, never>, Record<never, never>>,
    '/LigaTeams': RouteRecordInfo<'/LigaTeams', '/LigaTeams', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
